;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		.386p

		.model SMALL, SYSCALL

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		.DATA

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		extrn	SYSCALL	Chooser_RtnI:DWORD
		extrn	SYSCALL	Chooser_RtnF:DWORD
		extrn	SYSCALL	Chooser_RtnM:DWORD
		extrn	SYSCALL	Chooser_Result:DWORD

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		public	SYSCALL	LongRotate

LongRotate	dd	offset LongRotateInit

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		.CODE

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		extrn	SYSCALL	LongRotateI:PROC
		extrn	SYSCALL	LongRotateF:PROC
		extrn	SYSCALL	LongRotateM:PROC

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*

		extrn	SYSCALL	Chooser:PROC

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*
;void	LongRotate(S32 x, S32 z, S32 angle)	;

;#pragma	aux	LongRotate		\
;	parm		[eax] [ecx] [edx]	\
;	modify		[ebx esi edi]

LongRotateInit	proc

		mov	[Chooser_RtnI], offset LongRotateI	; Integer
		mov	[Chooser_RtnF], offset LongRotateF	; FPU
		mov	[Chooser_RtnM], offset LongRotateM	; MMX
		mov	[Chooser_Result], offset LongRotate	; Pointer
		jmp	Chooser

LongRotateInit	endp

;*様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様様*
;		The
		END
