#ifndef	PLAYACF_H
#define	PLAYACF_H

#ifdef __cplusplus
extern "C" {
#endif

//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
// COPY.ASM

//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
typedef	void	Func_CopyFrameDoubleXY(void *src)	;

#pragma aux Arg_CopyFrameDoubleXY	"*"	\
	parm caller	[esi]			\
	modify		[eax ebx ecx edx edi]

#pragma	aux (Arg_CopyFrameDoubleXY)	Func_CopyFrameDoubleXY

//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
extern	Func_CopyFrameDoubleXY	*CopyFrameDoubleXY	;

#pragma	aux	CopyFrameDoubleXY	"*"

//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß

#ifdef __cplusplus
}
#endif

// PLAYACF.CPP

//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
extern void 	InitAcf( void );
//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
extern char 	*GetAcfName( char *name ) ;
//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
extern S32  	GetNumAcf( char *name ) ;
//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
extern void 	PlayAllAcf( void ) ;
//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß
extern S32	PlayAcf( char * name);
//ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß

#endif	// PLAYACF_H
