/*
				POF.H

			   Gestion des pofs

*/

#ifndef	POF_H
#define	POF_H

//----------------------------------------------------------------------------------

#ifdef	LBA_EDITOR
#define	PATH_POF	"f:\\projet\\lba2\\datas\\pof\\"
#endif

//----------------------------------------------------------------------------------
extern S32 PofDisplay3DExt( S32 x, S32 y, S32 z, S32 num_pof, S32 scale, S32 rotation ) ;
//----------------------------------------------------------------------------------

#endif	/* POF_H */
