//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#ifndef	LIB_MENU_MENUFUNC
#define	LIB_MENU_MENUFUNC

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#ifdef __cplusplus
extern "C" {
#endif

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
extern void 		Message(char *message, S32 flag			);
extern S32 		Confirm(char *message, char *yes, char *no	);

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
extern void 		InputString(		T_MENU *ptrmenu, S32 handle,
						S32 maxchar		);

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
extern void 		SwitchButton(		T_MENU *ptrmenu, S32 handle);

extern void 		ChangeButtonFlags(	T_MENU *ptrmenu, S32 handle,
						S32 flags,	 S32 flagaff);

extern void 		ChangeButtonString(	T_MENU *ptrmenu, S32 handle,
						char *string,	 S32 flagaff);

extern void 		ChangeButtonValueLimit( T_MENU *ptrmenu, S32 handle,
						S32 valmin, 	 S32 valmax );

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
extern	S32		GetButtonFlags(		T_MENU *ptrmenu, S32 handle );

extern	char*		GetButtonString(	T_MENU *ptrmenu, S32 handle );

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
extern T_CLICK_BOX 	*GetPtrLcb(		T_MENU *ptrmenu,S32 handle  );

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#ifdef __cplusplus
}
#endif

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
#endif//LIB_MENU_MENUFUNC

//컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
