#ifndef	ADDKEYS_H
#define	ADDKEYS_H

#define	K_INF		86	// '<'
#define	K_EXC		53	// '!'

#define	K_CARRE		41	// '²'

#define	K_SCROLL_LCK	70	// 'Scroll Lock'
#define	K_PARENTHESE	12	// ')'
#define	K_EGAL		13	// '='
#define	K_CHAPEAU	26	// '^'
#define	K_DOLLAR	27	// '$'
#define	K_CAPS_LCK	58	// 'Caps Lock'
#define	K_OU		40	// 'ù'
#define	K_MUL		43	// '*'
#define	K_VIRGULE	50	// ','
#define	K_PT_VIRGULE	51	// ';'
#define	K_2_PTS		52	// ':'
#define	K_MUL_PAD	55	// '* NumPad'

#endif	// ADDKEYS_H
